@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FilterCommandParser" as FilterCommandParser LOGIC_COLOR
participant "f:FilterCommand" as FilterCommand LOGIC_COLOR
participant ":FilterPredicate" as FilterPredicate LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("filter s/applied t/tech")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("filter s/applied t/tech")
activate AddressBookParser

create FilterCommandParser
AddressBookParser -> FilterCommandParser
activate FilterCommandParser

FilterCommandParser --> AddressBookParser
deactivate FilterCommandParser

AddressBookParser -> FilterCommandParser : parse(" s/applied t/tech")
activate FilterCommandParser

FilterCommandParser -> FilterCommandParser : tokenize arguments
activate FilterCommandParser LOGIC_COLOR_T1
FilterCommandParser --> FilterCommandParser
deactivate FilterCommandParser

opt status provided
    FilterCommandParser -> FilterCommandParser : parseStatus("applied")
    activate FilterCommandParser LOGIC_COLOR_T1
    FilterCommandParser --> FilterCommandParser : Status.APPLIED
    deactivate FilterCommandParser
end

opt tags provided
    FilterCommandParser -> FilterCommandParser : parseTags(["tech"])
    activate FilterCommandParser LOGIC_COLOR_T1

    loop for each tag
        FilterCommandParser -> FilterCommandParser : parse tag
    end

    FilterCommandParser --> FilterCommandParser : tagKeywords
    deactivate FilterCommandParser
end

create FilterCommand
FilterCommandParser -> FilterCommand : new(status, tagKeywords)
activate FilterCommand

FilterCommand --> FilterCommandParser
deactivate FilterCommand

FilterCommandParser --> AddressBookParser : fc
deactivate FilterCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FilterCommandParser -[hidden]-> AddressBookParser
destroy FilterCommandParser

AddressBookParser --> LogicManager : fc
deactivate AddressBookParser

LogicManager -> FilterCommand : execute(m)
activate FilterCommand

create FilterPredicate
FilterCommand -> FilterPredicate : new(status, tagKeywords)
activate FilterPredicate
FilterPredicate --> FilterCommand
deactivate FilterPredicate

FilterCommand -> Model : updateFilteredCompanyList(predicate)
activate Model

Model --> FilterCommand
deactivate Model

FilterCommand -> Model : getFilteredCompanyList()
activate Model
Model --> FilterCommand : filteredList
deactivate Model

alt status and tags provided
    FilterCommand -> FilterCommand : generateSuccessMessage(count)
    activate FilterCommand LOGIC_COLOR_T1
    FilterCommand --> FilterCommand : "X companies listed!\nFiltered by status and tags"
    deactivate FilterCommand
else only status provided
    FilterCommand -> FilterCommand : generateSuccessMessage(count)
    activate FilterCommand LOGIC_COLOR_T1
    FilterCommand --> FilterCommand : "X companies listed!\nFiltered by status"
    deactivate FilterCommand
else only tags provided
    FilterCommand -> FilterCommand : generateSuccessMessage(count)
    activate FilterCommand LOGIC_COLOR_T1
    FilterCommand --> FilterCommand : "X companies listed!\nFiltered by tags"
    deactivate FilterCommand
end

create CommandResult
FilterCommand -> CommandResult : new(successMessage)
activate CommandResult

CommandResult --> FilterCommand
deactivate CommandResult

FilterCommand --> LogicManager : r
deactivate FilterCommand

[<--LogicManager : r
deactivate LogicManager
@enduml
